### PR TITLE
Add grass tiles based on official ones

### PR DESCRIPTION
**Pull request by M0REKZ**
Based on the Official SVGs released on discord, these are more accurate than the actual remakes

grass_main: just removed and moved some tiles.
grass_doodads_0.7: removed and modified some tiles.
grass_doodads: removed, moved, modified, and remade some tiles (a small stone and the columns).

*both grass doodads are still 960px of size, ill try to fix that

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Thanks for looking into this! The fence looks a bit like it has a glitched line on top.

before:
image

after:
image

**Comment by M0REKZ** [comment]
> The fence looks a bit like it has a glitched line on top.
fixed

btw i also forgot to mention: for remaking the columns i used a version without borderfix (yeah it had borderfix), so it could differ from the one found in DDNet mapres, but making it better quality.

**Comment by Jupeyy** [comment]
> btw i also forgot to mention: for remaking the columns i used a version without borderfix (yeah it had borderfix), so it could differ from the one found in DDNet mapres, but making it better quality.

Oh wow, good that you found that, bit sad for the mapres inside ddnet tbh xD

**Comment by ChillerDragon** [comment]
Thanks! I have to admit its a bit annoying to see the work I put so much time into replaced but omg I just realized how one of my bushes was super ugly haha.

**Pull request merged**
