### PR TITLE
Add grass_main

### PR DESCRIPTION
**Pull request by ChillerDragon**
screenshot_2021-12-16_13-42-44
screenshot_2021-12-16_13-42-52

### CODE REVIEW

**Comment by heinrich5991** [comment]
Looks good. How did you do this?

Mind posting a diff image?

**Comment by ChillerDragon** [comment]
> Looks good. How did you do this?

I drugged Landil and broke into his house to steal it from his drive.

XD

I just took the original png imported it into inkscape and re drew it manually.

> Mind posting a diff image?

Left side is vanilla right side is my png exported in 4096x resolution

**Comment by ChillerDragon** [comment]
diff

**Comment by ChillerDragon** [comment]
@heinrich5991 
> Looks good. How did you do this?

I recorded me doing the shotgun. https://www.youtube.com/watch?v=tPvFsi6CGNo
Thats how I do these remakes.

**Pull request merged**
