### PR TITLE
Jungle deathtiles remake

### PR DESCRIPTION
**Pull request by johannesHHM**
Not pixel perfect, but visually indistinguishable in game i think.

jd_compare_full
jd_compare_smoll

The original mapres has a bug on the vertical 1-spike spikes, where they are 0.5 pixels off, making them not line up with the cross tiles. I don't know your policy on these situations, but i fixed it in the remake.

jd_compare_bug

### CODE REVIEW

**Comment by def-** [comment]
Very cool

**Comment by ChillerDragon** [comment]
Thanks for working on this.

> The original mapres has a bug on the vertical 1-spike spikes, where they are 0.5 pixels off, making them not line up with the cross tiles. I don't know your policy on these situations, but i fixed it in the remake.

There is this issue discussing policy https://github.com/ddnet/ddnet-data-svg/issues/35

So there is not much or strict policy. Fixing bugs is totally cool! Good catch!

**Comment by ChillerDragon** [comment]
Had a closer look at the svg. Looks very clean! Do you mind sharing your process? Maybe we (mostly me) could learn something from how you created it. Do you import the reference image? I saw you used a grid. What is your process for ensuring the rotated spikes also align? I always use some cursed guidelines and calculate random numbers its such a mess haha. Do you use any tools or do you just hand draw some lines?

I get a Segmentation fault when running the build command from the pipeline. Could be a inkscape bug, a build script bug or my setup but it fails only on this svg so thats weird.

```
mkdir -p build/UHD
cd build/UHD
../../scripts/build.sh 3840 2160 ../..
```

```
exporting './skins/bluekitty.svg' to '/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/./skins/bluekitty.png' at 512x256
exporting './mapres/ddnet_walls.svg' to '/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/./mapres/ddnet_walls.png' at 2048x2048
exporting './skins/nanami.svg' to '/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/./skins/nanami.png' at 512x256
exporting './skins/x_spec.svg' to '/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/./skins/x_spec.png' at 512x256
exporting './skins/redstripe.svg' to '/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/./skins/redstripe.png' at 512x256
exporting './mapres/grass_main.svg' to '/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/./mapres/grass_main.png' at 2048x2048
exporting './gui_logo.svg' to '/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/./gui_logo.png' at 2934x840
exporting './mapres/jungle_deathtiles.svg' to '/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/./mapres/jungle_deathtiles.png' at 2048x2048
/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/../../scripts/build_single.sh: line 68:  8118 Segmentation fault      (core dumped) inkscape "$source_file" -C -w "$target_w" -h "$target_h" "$ink_export_flag" "$target_file" > /dev/null 2>&1
/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/../../scripts/build_single.sh: line 68:  8217 Segmentation fault      (core dumped) inkscape "$source_file" -C -w "$target_w" -h "$target_h" "$ink_export_flag" "$target_file" > /dev/null 2>&1
/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/../../scripts/build_single.sh: line 68:  8260 Segmentation fault      (core dumped) inkscape "$source_file" -C -w "$target_w" -h "$target_h" "$ink_export_flag" "$target_file" > /dev/null 2>&1
/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/../../scripts/build_single.sh: line 68:  8226 Segmentation fault      (core dumped) inkscape "$source_file" -C -w "$target_w" -h "$target_h" "$ink_export_flag" "$target_file" > /dev/null 2>&1
/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/../../scripts/build_single.sh: line 68:  8305 Segmentation fault      (core dumped) inkscape "$source_file" -C -w "$target_w" -h "$target_h" "$ink_export_flag" "$target_file" > /dev/null 2>&1
/home/chiler/Desktop/gaming/ddnet-data-svg/build/UHD/../../scripts/build_single.sh: line 68:  8297 Segmentation fault      (core dumped) inkscape "$source_file" -C -w "$target_w" -h "$target_h" "$ink_export_flag" "$target_file" > /dev/null 2>&1
done
```

The pixel diff looks very solid as well!

```
compare jungle_deathtiles_svg.png /usr/share/ddnet/data/mapres/jungle_deathtiles.png -compose src diff.png
```

diff


So very cool stuff! But I would like to delay the merge a bit until I or someone else finds time to investigate the inkscape segfault.

**Comment by def-** [comment]
A segfault in Inkscape is always an Inkscape bug. You might have an older Inkscape version of inkscape though, for me it works:
```
$ inkscape --version
Inkscape 1.2.2 (b0a8486541, 2022-12-01)
$ ../../scripts/build.sh 3840 2160 ../..
exporting './mapres/bg_cloud1.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/bg_cloud1.png' at 4096x2048
exporting './mapres/round_tiles.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/round_tiles.png' at 2048x2048
exporting './mapres/ddmax_freeze.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/ddmax_freeze.png' at 2048x2048
exporting './mapres/desert_background.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/desert_background.png' at 2540x832
exporting './mapres/sun.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/sun.png' at 1024x1024
exporting './mapres/winter_mountains2.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/winter_mountains2.png' at 2048x1024
exporting './mapres/desert_mountains_new_background.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/desert_mountains_new_background.png' at 3000x920
exporting './mapres/winter_mountains3.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/winter_mountains3.png' at 2048x1024
exporting './mapres/desert_mountains.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/desert_mountains.png' at 2048x1024
exporting './mapres/desert_mountains_new_foreground.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/desert_mountains_new_foreground.png' at 3000x1660
exporting './mapres/winter_mountains.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/winter_mountains.png' at 2048x1024
exporting './mapres/ddnet_walls.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/ddnet_walls.png' at 2048x2048
exporting './skins/x_ninja.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/x_ninja.png' at 512x256
exporting './mapres/bg_cloud3.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/bg_cloud3.png' at 2048x1024
exporting './mapres/moon.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/moon.png' at 2048x2048
exporting './skins/pinky.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/pinky.png' at 512x256
exporting './skins/twinbop.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/twinbop.png' at 512x256
exporting './skins/redbopp.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/redbopp.png' at 512x256
exporting './gui_logo.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./gui_logo.png' at 2934x840
exporting './skins/default.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/default.png' at 512x256
exporting './mapres/basic_freeze.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/basic_freeze.png' at 2048x2048
exporting './skins/x_spec.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/x_spec.png' at 512x256
exporting './skins/bluestripe.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/bluestripe.png' at 512x256
exporting './skins/whis.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/whis.png' at 512x256
exporting './skins/greensward.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/greensward.png' at 512x256
exporting './skins/cammostripes.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/cammostripes.png' at 512x256
exporting './mapres/bg_cloud2.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/bg_cloud2.png' at 4096x2048
exporting './skins/cammo.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/cammo.png' at 512x256
exporting './skins/twintri.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/twintri.png' at 512x256
exporting './skins/ghost.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/ghost.png' at 512x256
exporting './mapres/grass_doodads_0.7.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/grass_doodads_0.7.png' at 2048x2048
exporting './mapres/desert_mountains2.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/desert_mountains2.png' at 2048x1024
exporting './skins/warpaint.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/warpaint.png' at 512x256
exporting './skins/redstripe.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/redstripe.png' at 512x256
exporting './skins/mermydon.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/mermydon.png' at 512x256
exporting './skins/dino.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/dino.png' at 512x256
exporting './skins/kintaro_2.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/kintaro_2.png' at 512x256
exporting './mapres/jungle_doodads.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/jungle_doodads.png' at 2048x2048
exporting './skins/jeet.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/jeet.png' at 512x256
exporting './skins/random.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/random.png' at 512x256
exporting './skins/mermydon-coala.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/mermydon-coala.png' at 512x256
exporting './skins/nanami.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/nanami.png' at 512x256
exporting './skins/toptri.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/toptri.png' at 512x256
exporting './skins/saddo.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/saddo.png' at 512x256
exporting './skins/brownbear.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/brownbear.png' at 512x256
exporting './skins/limekitty.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/limekitty.png' at 512x256
exporting './skins/greyfox.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/greyfox.png' at 512x256
exporting './skins/coala.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/coala.png' at 512x256
exporting './skins/bluekitty.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./skins/bluekitty.png' at 512x256
exporting './mapres/grass_main.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/grass_main.png' at 2048x2048
exporting './mapres/jungle_deathtiles.svg' to '/home/deen/git/ddnet-data-svg/build/UHD/./mapres/jungle_deathtiles.png' at 2048x2048
done
```

**Comment by ChillerDragon** [comment]
Weird

```
$ /usr/bin/inkscape --version
Inkscape 1.2.2 (b0a8486541, 2022-12-01)
```

I do not have much time to debug that any time soon tho. If its just a me issue then I guess we can merge it.

**Comment by saltyElefant** [comment]
>What is your process for ensuring the rotated spikes also align? I always use some cursed guidelines and calculate random numbers its such a mess haha. Do you use any tools or do you just hand draw some lines?

If I understood you correctly: I simply group it with a tile-sized rectangle and use a grid + snapping.

https://user-images.githubusercontent.com/46008453/228492346-80e7914f-00bc-4160-982d-b58419f58250.mp4

**Pull request merged**
