### PR TITLE
Add Beast and Blacktee Redrawn

### PR DESCRIPTION
**Pull request by M0REKZ**
SVGs for Beast and Blacktee

### CODE REVIEW

**Comment by def-** [comment]
screenshot_2023-10-17_09-36-06
screenshot_2023-10-17_09-36-52
screenshot_2023-10-17_09-38-28
screenshot_2023-10-17_09-38-35
Looks about the same to me, maybe beast is 1 pixel less wide. Not sure if anything else has to be done or can be submitted now? @Jupeyy

**Comment by ChillerDragon** [comment]
Cool thanks @M0REKZ for contributing something :heart: 

Next time please [open an issue](https://github.com/ddnet/ddnet-data-svg/tree/36f1093a596f7b9ae17397daa0f005eddbd550d5#contributing) when you start working on it. So we can discuss stuff first before you spend time on it. Also to avoid two people working on the same texture.

image

Am I being too picky or could this be done cleaner?

Also it is not a vanilla skin. Not sure where and when it was introduced. But someone might have the original svg and might be willing to share it. As far as I know heinrich once managed to reach whis via the teeworlds forum.

**Comment by ChillerDragon** [comment]
Okay if that was an intentional decision thats cool with me. LGTM
@Jupeyy any objections otherwise I would vote for merge.

**Comment by ChillerDragon** [comment]
yes good catch lawyer jopsti we can also do this in a follow up pr

**Pull request merged**
