### PR TITLE
build.sh: Only run as many processes as the system has cores

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Aren't you on mac these days? Last time I used map `nproc` was not a thing and I had to use `sysctl -n hw.ncpu` wrapping it in a system independent `get_cores()` helper func seems more portable.

**Comment by def-** [comment]
I have coreutils installed on mac: https://formulae.brew.sh/formula/coreutils, so nproc is available. But let me make it work without that too.

**Comment by Jupeyy** [comment]
is it even using multiple cores for a single image now?

to me it looks like it still calls build_single.sh whihc didnt change

**Comment by def-** [comment]
It shouldn't, but I don't know what inkscape does internally.

**Pull request merged**
